version: 2.1
jobs:
  test:
    docker: 
      - image: yamsergey/swift-autoproxy-primary-build:0.0.5
    steps:
      - checkout
      - run: swift test
workflows:
  version: 2.1
  test:
    jobs:
      - test
